* Encoding: UTF-8.
* 07_03_PairedT.

* Dataset: 07_03_PairedT.sav.

EXAMINE VARIABLES=T1 T2 
  /COMPARE VARIABLE
  /PLOT=BOXPLOT
  /STATISTICS=NONE
  /NOTOTAL
  /MISSING=LISTWISE.

GRAPH
  /SCATTERPLOT(BIVAR)=T1 WITH T2
  /MISSING=LISTWISE.
* Manually add reference line at Y = X.

T-TEST PAIRS=T1 WITH T2 (PAIRED)
  /CRITERIA=CI(.9500)
  /MISSING=ANALYSIS.
